[package]
name = "plants_war"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.18.0"
ndarray = "0.16.1"
pbr = "1.1.1"
rand = "0.9.2"
rand_distr = "0.5.1"
rayon = "1.11.0"
shuffle = "0.1.7"
uuid = "1.18.1"
